name: 'jira-description-to-github-pr'
author: 'esdagh'
description: 'Copies a Jira description to a Pull Request description'
branding:
  icon: "check-circle"
  color: "green"
inputs:
  github-token:
    description: "Github access token"
    required: true
  jira-ticket-id:
    description: "Jira issue id"
    required: true
  jira-base-url: 
    description: "organization's jira url"
    required: true
  jira-api-version: 
    description: "api version to use, e.g. '2' or '3'"
    required: true
  jira-token:
    description: "Jira token"
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'